const nigerianStateCapitalCities = <String>[
  'Abeokuta',
  'Abakaliki',
  'Ado Ekiti',
  'Akure',
  'Asaba',
  'Awka',
  'Bauchi',
  'Benin City',
  'Birnin Kebbi',
  'Calabar',
  'Damaturu',
  'Dutse',
  'Enugu',
  'Gombe',
  'Gusau',
  'Ibadan',
  'Lagos',
  'Ilorin',
  'Jalingo',
  'Jos',
  'Kaduna',
  'Kano',
  'Katsina',
  'Lafia',
  'Lokoja',
  'Maiduguri',
  'Makurdi',
  'Minna',
  'Osogbo',
  'Owerri',
  'Port Harcourt',
  'Sokoto',
  'Umuahia',
  'Uyo',
  'Yenagoa',
  'Yola',
];

const nigerianCityBaseFees = <String, double>{
  'Lagos': 900,
  'Port Harcourt': 950,
  'Ibadan': 800,
  'Kano': 850,
  'Kaduna': 850,
};

double baseFeeForCity(String city) => nigerianCityBaseFees[city] ?? 850;
