#!/bin/bash

echo "Creating Firestore indexes for Environmental Surveillance..."
echo ""
echo "Please create these indexes in Firebase Console:"
echo ""
echo "1. Inspection Summary Report:"
echo "   Collection: environmental_inspections"
echo "   Fields: facilityId (Asc), inspectionDate (Desc)"
echo "   Link: Check error message for auto-generated link"
echo ""
echo "2. Sanitation Compliance Report:"
echo "   Collection: environmental_inspections"  
echo "   Fields: facilityId (Asc), inspectionType (Asc), inspectionDate (Desc)"
echo ""
echo "3. Sanitation Compliance with Department:"
echo "   Collection: environmental_inspections"
echo "   Fields: facilityId (Asc), inspectionType (Asc), department (Asc), inspectionDate (Desc)"
echo ""
echo "4. Issues & Actions with Findings Filter:"
echo "   Collection: environmental_inspections"
echo "   Fields: facilityId (Asc), findingsLevel (Asc), inspectionDate (Desc)"
echo ""
echo "5. Issues & Actions - Compliance Filter:"
echo "   Collection: environmental_inspections"
echo "   Fields: facilityId (Asc), inspectionType (Asc), compliancePercentage (Asc)"
echo ""
echo "Go to: https://console.firebase.google.com/project/lifecare-connect/firestore/indexes"
echo ""
echo "Click 'Add Index' and create each one manually"
echo "Indexes take 1-2 minutes to build"
