services:
  - type: web
    name: lifecare-connect-web
    env: static
    buildCommand: flutter build web --pwa-strategy=none && cp web/flutter_service_worker.js build/web/flutter_service_worker.js
    staticPublishPath: build/web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: agora-token-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node agora-token-server.js
    rootDir: lifecare_connect
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
