class HaiQuestionnaireField {
  final String id;
  final String name;
  final String label;
  final String section;
  final String type;
  final bool required;
  final List<HaiQuestionnaireOption> options;
  final String relevant;
  final Map<String, dynamic> calculation;
  final Map<String, dynamic> metadata;

  const HaiQuestionnaireField({
    this.id = '',
    required this.name,
    required this.label,
    required this.section,
    this.type = 'text',
    this.required = false,
    this.options = const [],
    this.relevant = '',
    this.calculation = const {},
    this.metadata = const {},
  });
}

class HaiQuestionnaireOption {
  final String value;
  final String label;

  const HaiQuestionnaireOption(this.value, this.label);
}

const haiQuestionnaireSections = <String>[
  "Patient Biodata",
  "Antimicrobial data",
  "Patient Risk Factors",
  "Patient HAIs",
  "Patient Microorganism",
];

const haiQuestionnaireFields = <HaiQuestionnaireField>[
  HaiQuestionnaireField(
    name: "Department",
    label: "2. Department",
    section: "Patient Biodata",
    type: "select",
    required: true,
    options: [
      HaiQuestionnaireOption("surgery", "Surgery"),
      HaiQuestionnaireOption("medicine", "Medicine"),
      HaiQuestionnaireOption("paediatric", "Paediatric"),
      HaiQuestionnaireOption("o_g", "O&G"),
      HaiQuestionnaireOption("other", "Other"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_3_Surgical_Wards",
    label: "3. Surgical Wards",
    section: "Patient Biodata",
    type: "select",
    required: true,
    relevant: r"${Department} = 'surgery'",
    options: [
      HaiQuestionnaireOption("male_surgical_ward", "Male Surgical Ward"),
      HaiQuestionnaireOption("female_surgical_ward", "Female Surgical Ward"),
      HaiQuestionnaireOption("male_orthopaedic_ward", "Male Orthopaedic Ward"),
      HaiQuestionnaireOption(
        "paediatric_surgical_ward",
        "Paediatric Surgical Ward",
      ),
      HaiQuestionnaireOption("urology_ward", "Urology Ward"),
      HaiQuestionnaireOption("burns___plastic_ward", "Burns & Plastic Ward"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_4_Medical_Wards",
    label: "4. Medical Wards",
    section: "Patient Biodata",
    type: "select",
    required: true,
    relevant: r"${Department} = 'medicine'",
    options: [
      HaiQuestionnaireOption("male_medical_ward", "Male Medical Ward"),
      HaiQuestionnaireOption("female_medical_ward", "Female Medical Ward"),
      HaiQuestionnaireOption("isolation_ward", "Isolation Ward"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_5_O_G_Wards",
    label: "5. O&G Wards",
    section: "Patient Biodata",
    type: "select",
    required: true,
    relevant: r"${Department} = 'o_g'",
    options: [
      HaiQuestionnaireOption("obstetric_ward", "Obstetric Ward"),
      HaiQuestionnaireOption("gynae_ward", "Gynae Ward"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_6_Paediatric_Wards",
    label: "6. Paediatric Wards",
    section: "Patient Biodata",
    type: "select",
    required: true,
    relevant: r"${Department} = 'paediatric'",
    options: [
      HaiQuestionnaireOption(
        "paediatric_medical_ward",
        "Paediatric Medical Ward",
      ),
      HaiQuestionnaireOption(
        "special_baby_care_unit",
        "Special Baby Care Unit",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_7_Other_Wards",
    label: "7. Other Wards",
    section: "Patient Biodata",
    type: "select",
    required: true,
    relevant: r"${Department} = 'other'",
    options: [
      HaiQuestionnaireOption("oncology_ward", "Oncology Ward"),
      HaiQuestionnaireOption("amenity_ward", "Amenity Ward"),
      HaiQuestionnaireOption("intensive_care_unit", "Intensive Care Unit"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_8_Date_of_admission",
    label: "8. Date of admission",
    section: "Patient Biodata",
    type: "date",
    required: true,
  ),
  HaiQuestionnaireField(
    name: "_9_Hospital_number",
    label: "9. Hospital number",
    section: "Patient Biodata",
    type: "integer",
    required: true,
  ),
  HaiQuestionnaireField(
    name: "_10_Patient_Age",
    label: "10. Patient Age",
    section: "Patient Biodata",
    type: "integer",
    required: true,
  ),
  HaiQuestionnaireField(
    name: "_11_Patient_Gender",
    label: "11. Patient Gender",
    section: "Patient Biodata",
    type: "select",
    required: true,
    options: [
      HaiQuestionnaireOption("male", "Male"),
      HaiQuestionnaireOption("female", "Female"),
      HaiQuestionnaireOption("unknown", "Unknown"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_12_Patient_specialty",
    label: "12. Patient specialty",
    section: "Patient Biodata",
    type: "select",
    required: true,
    options: [
      HaiQuestionnaireOption("medical", "Medical"),
      HaiQuestionnaireOption(
        "gynecology___obstetrics",
        "Gynecology & Obstetrics",
      ),
      HaiQuestionnaireOption("surgical", "Surgical"),
      HaiQuestionnaireOption("pediatrics", "Pediatrics"),
      HaiQuestionnaireOption("neonatology", "Neonatology"),
      HaiQuestionnaireOption("geriatrics", "Geriatrics"),
      HaiQuestionnaireOption("others", "Others"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_13_Clinical_diagnosis",
    label: "13. Clinical diagnosis",
    section: "Patient Biodata",
    type: "text",
    required: true,
  ),
  HaiQuestionnaireField(
    name: "Antimicrobials",
    label: "14. Antimicrobials",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_15_Number_of_Current_Antimicrobials",
    label: "15. Number of Current Antimicrobials",
    section: "Antimicrobial data",
    type: "integer",
    required: true,
    relevant: r"${Antimicrobials} = 'yes'",
  ),
  HaiQuestionnaireField(
    name: "Antimicrobials_001",
    label: "16. Antimicrobials:",
    section: "Antimicrobial data",
    type: "multiselect",
    required: true,
    relevant: r"${Antimicrobials} = 'yes'",
    options: [
      HaiQuestionnaireOption("ampicillin", "Ampicillin"),
      HaiQuestionnaireOption("ampicillin_sulbactam", "Ampicillin Sulbactam"),
      HaiQuestionnaireOption("amoxicillin", "Amoxicillin"),
      HaiQuestionnaireOption("co_amoxiclav", "Co-Amoxiclav"),
      HaiQuestionnaireOption("amikacin", "Amikacin"),
      HaiQuestionnaireOption("azithromycin", "Azithromycin"),
      HaiQuestionnaireOption("ceftriaxone", "Ceftriaxone"),
      HaiQuestionnaireOption("ceftriaxone_sulbactam", "Ceftriaxone Sulbactam"),
      HaiQuestionnaireOption("ceftriaxon_tozabactam", "Ceftriaxon Tozabactam"),
      HaiQuestionnaireOption("ceftazidime", "Ceftazidime"),
      HaiQuestionnaireOption("cefixime", "Cefixime"),
      HaiQuestionnaireOption("cefuroxime", "Cefuroxime"),
      HaiQuestionnaireOption("cefodoxine", "Cefodoxine"),
      HaiQuestionnaireOption("cefoxitin", "Cefoxitin"),
      HaiQuestionnaireOption("cefotaxime", "Cefotaxime"),
      HaiQuestionnaireOption("carbenicillin", "Carbenicillin"),
      HaiQuestionnaireOption("cefdinor", "Cefdinor"),
      HaiQuestionnaireOption("cefepime", "Cefepime"),
      HaiQuestionnaireOption("ciprofloxacin", "Ciprofloxacin"),
      HaiQuestionnaireOption("clarithromycin", "Clarithromycin"),
      HaiQuestionnaireOption("chloramphenicol", "Chloramphenicol"),
      HaiQuestionnaireOption("clindamycin", "Clindamycin"),
      HaiQuestionnaireOption("cloxacillin", "Cloxacillin"),
      HaiQuestionnaireOption("cotrimoxazole", "Cotrimoxazole"),
      HaiQuestionnaireOption("colistin", "Colistin"),
      HaiQuestionnaireOption("doxycycline", "Doxycycline"),
      HaiQuestionnaireOption("erythromycin", "Erythromycin"),
      HaiQuestionnaireOption("gentamycin", "Gentamycin"),
      HaiQuestionnaireOption("levofloxacin", "Levofloxacin"),
      HaiQuestionnaireOption("nitrofurantoin", "Nitrofurantoin"),
      HaiQuestionnaireOption("mupirocin", "Mupirocin"),
      HaiQuestionnaireOption("tigecycline", "Tigecycline"),
      HaiQuestionnaireOption("ofloxacin", "Ofloxacin"),
      HaiQuestionnaireOption("piperacillin", "Piperacillin"),
      HaiQuestionnaireOption("meropenem", "Meropenem"),
      HaiQuestionnaireOption("tetracycline", "Tetracycline"),
      HaiQuestionnaireOption("penecillin", "Penecillin"),
      HaiQuestionnaireOption("vancomycin", "Vancomycin"),
      HaiQuestionnaireOption("pefloxacin", "Pefloxacin"),
      HaiQuestionnaireOption("imupenem", "Imupenem"),
      HaiQuestionnaireOption("novobiocin", "Novobiocin"),
      HaiQuestionnaireOption("metronidazole", "Metronidazole"),
      HaiQuestionnaireOption("secnidazole", "Secnidazole"),
      HaiQuestionnaireOption("others__specify", "Others (specify)"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_17_Please_specify",
    label: "17. Please specify:",
    section: "Antimicrobial data",
    type: "text",
    required: true,
    relevant: r"selected(${Antimicrobials_001}, 'others__specify')",
  ),
  HaiQuestionnaireField(
    name: "_18_Duration_of_antimicrobials_in_days",
    label: "18. Duration of antimicrobials (in days)",
    section: "Antimicrobial data",
    type: "integer",
    required: true,
    relevant: r"${Antimicrobials} = 'yes'",
  ),
  HaiQuestionnaireField(
    name: "_19_Reasons_for_anti_eatment_in_the_notes",
    label: "19. Reasons for antimicrobial treatment in the notes?",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant: r"${Antimicrobials} = 'yes'",
    options: [
      HaiQuestionnaireOption("empirical_treatment", "Yes"),
      HaiQuestionnaireOption("targeted_treatment", "No"),
      HaiQuestionnaireOption("not_on_antibiotics", "Not on antibiotics"),
      HaiQuestionnaireOption("prophylactic_treatment", "Unknown"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_20_Stop_and_Review_date",
    label: "20. Stop and Review date?",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant: r"${Antimicrobials} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Antibiotics_indication",
    label: "21. Antibiotics indication",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant: r"${Antimicrobials} = 'yes'",
    options: [
      HaiQuestionnaireOption(
        "cns_infection",
        "Treatment of community acquired infection (Empirical)",
      ),
      HaiQuestionnaireOption(
        "uti_infection",
        "Treatment of community acquired infection (Targeted)",
      ),
      HaiQuestionnaireOption(
        "gi_infection",
        "Treatment of hospital acquired infection (Empirical)",
      ),
      HaiQuestionnaireOption(
        "respiratory_infection",
        "Treatment of hospital acquired infection (Targeted)",
      ),
      HaiQuestionnaireOption(
        "skin___soft_tissue_infection",
        "Surgical prophylaxis",
      ),
      HaiQuestionnaireOption("cvs_infection", "Medical prophylaxis"),
      HaiQuestionnaireOption("eye_infection", "Unknown Indication, verified"),
      HaiQuestionnaireOption(
        "obstetric___gynaecology_infection",
        "No information",
      ),
      HaiQuestionnaireOption("ent_infection", "Others"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_22_Please_specify",
    label: "22. Please specify",
    section: "Antimicrobial data",
    type: "text",
    required: true,
    relevant: r"${Antibiotics_indication} = 'ent_infection'",
  ),
  HaiQuestionnaireField(
    name: "Duration_for_surgical_prophylaxis",
    label: "Duration for surgical prophylaxis",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant: r"${Antibiotics_indication} = 'skin___soft_tissue_infection'",
    options: [
      HaiQuestionnaireOption("_24_hours", "<24 hours"),
      HaiQuestionnaireOption("24hr___3days", "24hr - 3days"),
      HaiQuestionnaireOption("_3_days", ">3 days"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_23_Was_there_a_switch_from_pa",
    label: "23. Was there a switch from parenteral to oral antibiotics",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant: r"${Antimicrobials} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption(
        "no__but_the_patient_was_clinic",
        "No, but the patient was clinically stable and eligible for switch",
      ),
      HaiQuestionnaireOption(
        "no__patient_was_not_clinically",
        "No, patient was not clinically stable",
      ),
      HaiQuestionnaireOption(
        "not_applicable__e_g__short_cou",
        "Not applicable (e.g., short course completed IV, Never been on IV)",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_24_If_no_switch_was_made_desp",
    label:
        "24. If no switch was made despite clinical stability, what was the main reason?",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant:
        r"${_23_Was_there_a_switch_from_pa} = 'no__but_the_patient_was_clinic'",
    options: [
      HaiQuestionnaireOption(
        "no_oral_alternative_available",
        "No oral alternative available",
      ),
      HaiQuestionnaireOption(
        "concern_about_absorption_or_bi",
        "Concern about absorption or bioavailability",
      ),
      HaiQuestionnaireOption(
        "lack_of_clear_guideline_policy",
        "Lack of clear guideline/policy",
      ),
      HaiQuestionnaireOption(
        "clinician_preference_or_habit",
        "Clinician preference or habit",
      ),
      HaiQuestionnaireOption("patient_refusal", "Patient refusal"),
      HaiQuestionnaireOption(
        "other__please_specify_",
        "Other (please specify): ___________",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_25_Please_specify",
    label: "25. Please specify",
    section: "Antimicrobial data",
    type: "text",
    required: true,
    relevant: r"${_24_If_no_switch_was_made_desp} = 'other__please_specify_'",
  ),
  HaiQuestionnaireField(
    name: "_26_Prescriber_s_status",
    label: "26. Prescriber's status",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant: r"${Antimicrobials} = 'yes'",
    options: [
      HaiQuestionnaireOption("consultant", "Consultant"),
      HaiQuestionnaireOption("registrar", "Registrar"),
      HaiQuestionnaireOption("medical_officer", "Medical officer"),
      HaiQuestionnaireOption(
        "medical_intern__house_officer",
        "Medical Intern (House officer)",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_27_Has_the_patient_used_any_a",
    label: "27. Has the patient used any antibiotics in the past 90 days?",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
      HaiQuestionnaireOption("not_sure", "Not sure"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Antimicrobials_001_001",
    label: "28. If yes, please specify",
    section: "Antimicrobial data",
    type: "multiselect",
    required: true,
    relevant: r"${_27_Has_the_patient_used_any_a} = 'yes'",
    options: [
      HaiQuestionnaireOption("ampicillin", "Ampicillin"),
      HaiQuestionnaireOption("ampicillin_sulbactam", "Ampicillin Sulbactam"),
      HaiQuestionnaireOption("amoxicillin", "Amoxicillin"),
      HaiQuestionnaireOption("co_amoxiclav", "Co-Amoxiclav"),
      HaiQuestionnaireOption("amikacin", "Amikacin"),
      HaiQuestionnaireOption("azithromycin", "Azithromycin"),
      HaiQuestionnaireOption("ceftriaxone", "Ceftriaxone"),
      HaiQuestionnaireOption("ceftriaxone_sulbactam", "Ceftriaxone Sulbactam"),
      HaiQuestionnaireOption("ceftriaxon_tozabactam", "Ceftriaxon Tozabactam"),
      HaiQuestionnaireOption("ceftazidime", "Ceftazidime"),
      HaiQuestionnaireOption("cefixime", "Cefixime"),
      HaiQuestionnaireOption("cefuroxime", "Cefuroxime"),
      HaiQuestionnaireOption("cefodoxine", "Cefodoxine"),
      HaiQuestionnaireOption("cefoxitin", "Cefoxitin"),
      HaiQuestionnaireOption("cefotaxime", "Cefotaxime"),
      HaiQuestionnaireOption("carbenicillin", "Carbenicillin"),
      HaiQuestionnaireOption("cefdinor", "Cefdinor"),
      HaiQuestionnaireOption("cefepime", "Cefepime"),
      HaiQuestionnaireOption("ciprofloxacin", "Ciprofloxacin"),
      HaiQuestionnaireOption("clarithromycin", "Clarithromycin"),
      HaiQuestionnaireOption("chloramphenicol", "Chloramphenicol"),
      HaiQuestionnaireOption("clindamycin", "Clindamycin"),
      HaiQuestionnaireOption("cloxacillin", "Cloxacillin"),
      HaiQuestionnaireOption("cotrimoxazole", "Cotrimoxazole"),
      HaiQuestionnaireOption("colistin", "Colistin"),
      HaiQuestionnaireOption("doxycycline", "Doxycycline"),
      HaiQuestionnaireOption("erythromycin", "Erythromycin"),
      HaiQuestionnaireOption("gentamycin", "Gentamycin"),
      HaiQuestionnaireOption("levofloxacin", "Levofloxacin"),
      HaiQuestionnaireOption("nitrofurantoin", "Nitrofurantoin"),
      HaiQuestionnaireOption("mupirocin", "Mupirocin"),
      HaiQuestionnaireOption("tigecycline", "Tigecycline"),
      HaiQuestionnaireOption("ofloxacin", "Ofloxacin"),
      HaiQuestionnaireOption("piperacillin", "Piperacillin"),
      HaiQuestionnaireOption("meropenem", "Meropenem"),
      HaiQuestionnaireOption("tetracycline", "Tetracycline"),
      HaiQuestionnaireOption("penecillin", "Penecillin"),
      HaiQuestionnaireOption("vancomycin", "Vancomycin"),
      HaiQuestionnaireOption("pefloxacin", "Pefloxacin"),
      HaiQuestionnaireOption("imupenem", "Imupenem"),
      HaiQuestionnaireOption("novobiocin", "Novobiocin"),
      HaiQuestionnaireOption("metronidazole", "Metronidazole"),
      HaiQuestionnaireOption("secnidazole", "Secnidazole"),
      HaiQuestionnaireOption("others__specify", "Others (specify)"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_29_What_was_the_reason_for_th",
    label: "29. What was the reason for the antibiotic use?",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant: r"${_27_Has_the_patient_used_any_a} = 'yes'",
    options: [
      HaiQuestionnaireOption("respiratory_infection", "Respiratory infection"),
      HaiQuestionnaireOption(
        "urinary_tract_infection",
        "Urinary tract infection",
      ),
      HaiQuestionnaireOption(
        "skin_soft_tissue_infection",
        "Skin/soft tissue infection",
      ),
      HaiQuestionnaireOption(
        "gastrointestinal_infection",
        "Gastrointestinal infection",
      ),
      HaiQuestionnaireOption(
        "prophylactic_use__e_g__before_surgery",
        "Prophylactic use (e.g., before surgery)",
      ),
      HaiQuestionnaireOption("other__please_specify", "Other (please specify)"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_30_Please_specify",
    label: "30. Please specify",
    section: "Antimicrobial data",
    type: "text",
    required: true,
    relevant: r"${_29_What_was_the_reason_for_th} = 'other__please_specify'",
  ),
  HaiQuestionnaireField(
    name: "_31_Was_the_antibiot_lthcare_professional",
    label: "31. Was the antibiotic prescribed by a healthcare professional?",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant: r"${_27_Has_the_patient_used_any_a} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption(
        "no__self_medication_or_pharmacy",
        "No (self-medication or pharmacy)",
      ),
      HaiQuestionnaireOption("not_sure", "Not sure"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_32_Was_the_antibiot_pleted_as_prescribed",
    label: "32. Was the antibiotic course completed as prescribed?",
    section: "Antimicrobial data",
    type: "select",
    required: true,
    relevant: r"${_27_Has_the_patient_used_any_a} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
      HaiQuestionnaireOption("not_sure", "Not sure"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Type_of_risk",
    label: "33. Type of risk",
    section: "Patient Risk Factors",
    type: "multiselect",
    required: true,
    options: [
      HaiQuestionnaireOption("medical_device", "Medical Device"),
      HaiQuestionnaireOption("surgical_procedure", "Surgical Procedure"),
      HaiQuestionnaireOption("prolong_hospital_stay", "Prolong Hospital Stay"),
      HaiQuestionnaireOption("none", "None"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Type_of_Devices",
    label: "34. Type of Devices",
    section: "Patient Risk Factors",
    type: "multiselect",
    required: true,
    relevant: r"selected(${Type_of_risk}, 'medical_device')",
    options: [
      HaiQuestionnaireOption("urinary_catheter", "Urinary Catheter"),
      HaiQuestionnaireOption("ng_tube", "NG Tube"),
      HaiQuestionnaireOption("invasive_ventilator", "Invasive Ventilator"),
      HaiQuestionnaireOption("oxygen_mask", "Intranasal Oxygen"),
      HaiQuestionnaireOption("chest_tube", "Chest Tube"),
      HaiQuestionnaireOption("tracheostomy_tube", "Tracheostomy Tube"),
      HaiQuestionnaireOption(
        "central_venous_catheter",
        "Central Venous Catheter",
      ),
      HaiQuestionnaireOption(
        "peripheral_venous_catheter",
        "Peripheral Venous Catheter",
      ),
      HaiQuestionnaireOption("surgical_drain", "Surgical Drain"),
      HaiQuestionnaireOption("implant", "Implant"),
      HaiQuestionnaireOption("other_devices", "Other devices"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_35_Please_specify",
    label: "35. Please specify",
    section: "Patient Risk Factors",
    type: "text",
    required: true,
    relevant: r"selected(${Type_of_Devices}, 'other_devices')",
  ),
  HaiQuestionnaireField(
    name: "Date_of_device_insertion",
    label: "35a. Date of device insertion",
    section: "Patient Risk Factors",
    type: "date",
    required: true,
    relevant: r"selected(${Type_of_risk}, 'medical_device')",
  ),
  HaiQuestionnaireField(
    name: "Duration_on_device_days",
    label: "35b. Duration on device (days)",
    section: "Patient Risk Factors",
    type: "text",
    required: true,
    relevant:
        r"selected(${Type_of_risk}, 'medical_device') and ${Date_of_device_insertion} != ''",
  ),
  HaiQuestionnaireField(
    name: "Type_of_Surgical_Procedure",
    label: "36. Type of Surgical Procedure",
    section: "Patient Risk Factors",
    type: "select",
    required: true,
    relevant: r"selected(${Type_of_risk}, 'surgical_procedure')",
    options: [
      HaiQuestionnaireOption("general_surgery", "General surgery"),
      HaiQuestionnaireOption("orthopedic_surgery", "Orthopedic Surgery"),
      HaiQuestionnaireOption("neurosurgery", "Neurosurgery"),
      HaiQuestionnaireOption(
        "obstetrics_and_gynecology",
        "Obstetrics and Gynecology",
      ),
      HaiQuestionnaireOption("urologic_surgery", "Urologic Surgery"),
      HaiQuestionnaireOption(
        "gastrointestinal__gi__surgery",
        "Gastrointestinal (GI) Surgery",
      ),
      HaiQuestionnaireOption(
        "ent__ear__nose__throat__surger",
        "ENT (Ear, Nose, Throat) Surgery",
      ),
      HaiQuestionnaireOption(
        "maxillofacial__dental__surgery",
        "Maxillofacial (Dental) Surgery",
      ),
      HaiQuestionnaireOption(
        "plastic_and_reconstructive_sur",
        "Plastic and Reconstructive Surgery",
      ),
      HaiQuestionnaireOption("ophthalmic_surgery", "Ophthalmic Surgery"),
      HaiQuestionnaireOption("vascular_surgery", "Paediatrics Surgery"),
      HaiQuestionnaireOption(
        "cardiothoracic_surgery",
        "Cardiothoracic Surgery",
      ),
      HaiQuestionnaireOption("others", "Others"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_38_Please_specify",
    label: "38. Please specify",
    section: "Patient Risk Factors",
    type: "text",
    required: true,
    relevant: r"${Type_of_Surgical_Procedure} = 'others'",
  ),
  HaiQuestionnaireField(
    name: "_39_Please_specify_surgery_type",
    label: "39. Please specify surgery type",
    section: "Patient Risk Factors",
    type: "text",
    required: true,
    relevant:
        r"${Type_of_Surgical_Procedure} = 'general_surgery' or ${Type_of_Surgical_Procedure} = 'orthopedic_surgery' or ${Type_of_Surgical_Procedure} = 'neurosurgery' or ${Type_of_Surgical_Procedure} = 'obstetrics_and_gynecology' or ${Type_of_Surgical_Procedure} = 'urologic_surgery' or ${Type_of_Surgical_Procedure} = 'gastrointestinal__gi__surgery' or ${Type_of_Surgical_Procedure} = 'ent__ear__nose__throat__surger' or ${Type_of_Surgical_Procedure} = 'plastic_and_reconstructive_sur' or ${Type_of_Surgical_Procedure} = 'ophthalmic_surgery' or ${Type_of_Surgical_Procedure} = 'vascular_surgery' or ${Type_of_Surgical_Procedure} = 'cardiothoracic_surgery' or ${Type_of_Surgical_Procedure} = 'others'",
  ),
  HaiQuestionnaireField(
    name: "_40_Duration_of_hosp_ays_weeks_or_months",
    label: "40. Duration of hospital stay (in days, weeks or months)",
    section: "Patient Risk Factors",
    type: "text",
    required: true,
    relevant: r"selected(${Type_of_risk}, 'prolong_hospital_stay')",
  ),
  HaiQuestionnaireField(
    name: "HAIs",
    label: "41. HAIs",
    section: "Patient HAIs",
    type: "select",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "The_HAIs_diagnosis_is_based_on",
    label: "42. Is the HAIs diagnosis is based on laboratory culture?",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${HAIs} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Type_of_HAIs",
    label: "43. Type of HAIs",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${HAIs} = 'yes'",
    options: [
      HaiQuestionnaireOption(
        "urinary_tract_infection",
        "Urinary Tract Infection",
      ),
      HaiQuestionnaireOption("ssi", "SSI"),
      HaiQuestionnaireOption("sst", "SST"),
      HaiQuestionnaireOption("bsi", "BSI"),
      HaiQuestionnaireOption("respiratory_infection", "Respiratory Infection"),
      HaiQuestionnaireOption("others", "Others"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_44_Please_specify",
    label: "44. Please specify",
    section: "Patient HAIs",
    type: "text",
    required: true,
    relevant: r"${Type_of_HAIs} = 'others'",
  ),
  HaiQuestionnaireField(
    name: "_45_Specify_type_of_SSI",
    label: "45. Specify type of SSI",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${Type_of_HAIs} = 'ssi'",
    options: [
      HaiQuestionnaireOption("ssi_superficial", "SSI-Superficial"),
      HaiQuestionnaireOption("ssi_deep", "SSI-Deep"),
      HaiQuestionnaireOption("ssi_organ_space", "SSI-Organ/space"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_46_Specify_type",
    label: "46. Specify type",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${Type_of_HAIs} = 'sst'",
    options: [
      HaiQuestionnaireOption("bed_sore", "Bed sore"),
      HaiQuestionnaireOption("burns", "Burns"),
      HaiQuestionnaireOption("bruises", "Bruises from RTA"),
      HaiQuestionnaireOption("others", "Others"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_47_Specific_Reason_ied_system_infection",
    label: "47. Specific Reason for Unidentified system infection",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant:
        r"${The_HAIs_diagnosis_is_based_on} = 'no' and ${Type_of_HAIs} = 'bsi'",
    options: [
      HaiQuestionnaireOption(
        "sys_csep1__no_resources_to_do_blood_cult",
        "SYS-CSEP1 (No Resources to do blood culture)",
      ),
      HaiQuestionnaireOption(
        "sys_csep2__blood_culture_not_done",
        "SYS-CSEP2 (Blood culture not done)",
      ),
      HaiQuestionnaireOption(
        "sys_csep3__no_organism_in_blood_culture",
        "SYS-CSEP3 (No organism in blood culture)",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_48_Specify_Culture_Status",
    label: "48. Specify Culture Status",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${Type_of_HAIs} = 'urinary_tract_infection'",
    options: [
      HaiQuestionnaireOption(
        "uti_a__microbiological_confirmation",
        "UTI-A (Microbiological confirmation)",
      ),
      HaiQuestionnaireOption(
        "uti_b__no_microbiological_confirmation",
        "UTI-B (No Microbiological confirmation)",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_49_Specify_type",
    label: "49. Specify type",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${Type_of_HAIs} = 'respiratory_infection'",
    options: [
      HaiQuestionnaireOption(
        "clipn__no_microbiology_confirmation",
        "CliPN (No Microbiology confirmation)",
      ),
      HaiQuestionnaireOption(
        "misuspn__microbiological_suspicion",
        "MisusPN (Microbiological suspicion)",
      ),
      HaiQuestionnaireOption(
        "micpn__microbiological_confirmation",
        "MicPN (Microbiological confirmation)",
      ),
      HaiQuestionnaireOption("lri_bron", "LRI-BRON"),
      HaiQuestionnaireOption("lri_lung", "LRI-LUNG"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_50_Specify_source_of_infection",
    label: "50. Specify source of infection",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${Type_of_HAIs} = 'ssi'",
    options: [
      HaiQuestionnaireOption(
        "contaminated_surgical_area",
        "Contaminated surgical area",
      ),
      HaiQuestionnaireOption(
        "uncontaminated_surgical_area",
        "Uncontaminated surgical area",
      ),
      HaiQuestionnaireOption("improper_wound_care", "Improper wound care"),
      HaiQuestionnaireOption(
        "infrequent_dressing_changes",
        "Infrequent dressing changes",
      ),
      HaiQuestionnaireOption(
        "premature_wound_exposure",
        "Premature wound exposure",
      ),
      HaiQuestionnaireOption(
        "use_of_non_sterile_materials",
        "Use of non-sterile materials",
      ),
      HaiQuestionnaireOption(
        "hematoma_or_seroma_formation",
        "Hematoma or seroma formation",
      ),
      HaiQuestionnaireOption(
        "use_of_drains_or_catheters",
        "Use of drains or catheters",
      ),
      HaiQuestionnaireOption(
        "patient_self_contamination",
        "Patient self-contamination",
      ),
      HaiQuestionnaireOption("uo__unknown_source", "UO (Unknown source)"),
      HaiQuestionnaireOption("un__no_information", "UN (No information)"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_51_Specify_source_of_infection",
    label: "51. Specify source of infection",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${Type_of_HAIs} = 'bsi'",
    options: [
      HaiQuestionnaireOption("presence_of_cvc", "Presence of CVC"),
      HaiQuestionnaireOption("presence_pvc", "Presence PVC"),
      HaiQuestionnaireOption(
        "sec__secondary_infection",
        "SEC (Secondary Infection)",
      ),
      HaiQuestionnaireOption("uo__unknown_source", "UO (Unknown source)"),
      HaiQuestionnaireOption("un__no_information", "UN (No information)"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_52_Specify_source_of_infection",
    label: "52. Specify source of infection",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${Type_of_HAIs} = 'urinary_tract_infection'",
    options: [
      HaiQuestionnaireOption("presence_of_cvc", "Urinary Catheter"),
      HaiQuestionnaireOption("uo__unknown_source", "UO (Unknown source)"),
      HaiQuestionnaireOption("un__no_information", "UN (No information)"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_53_Specify_source_of_infection",
    label: "53. Specify source of infection",
    section: "Patient HAIs",
    type: "select",
    required: true,
    relevant: r"${Type_of_HAIs} = 'respiratory_infection'",
    options: [
      HaiQuestionnaireOption(
        "presence_of_cvc",
        "Presence of ETT/chest tube/NGT",
      ),
      HaiQuestionnaireOption("uo__unknown_source", "UO (Unknown source)"),
      HaiQuestionnaireOption("un__no_information", "UN (No information)"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Culture_requested",
    label: "54. Culture requested?",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_44_Do_the_same_patient_have_a",
    label: "55. Do the same patient have additional culture request?",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Culture_requested} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_45_Specimen_collected",
    label: "56. Specimen collected?",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Culture_requested} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_57_Date_of_sample_collection",
    label: "57. Date of sample collection",
    section: "Patient Microorganism",
    type: "date",
    required: true,
    relevant: r"${_45_Specimen_collected} = 'yes'",
  ),
  HaiQuestionnaireField(
    name: "Multiple_pathogen_growth",
    label: "58. Multiple pathogen growth?",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${_45_Specimen_collected} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "From_the_same_sample",
    label: "59. From the same sample?",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Multiple_pathogen_growth} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_60_Type_of_Sample_Collected",
    label: "60. Type of Sample Collected",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${_45_Specimen_collected} = 'yes'",
    options: [
      HaiQuestionnaireOption("wound_swab", "Wound swab"),
      HaiQuestionnaireOption("urine", "Urine"),
      HaiQuestionnaireOption("blood", "Blood"),
      HaiQuestionnaireOption("sputum", "Sputum"),
      HaiQuestionnaireOption("tracheal_aspirate", "Tracheal aspirate"),
      HaiQuestionnaireOption("tissue_mcs", "Tissue MCS"),
      HaiQuestionnaireOption("bone_mcs", "Bone MCS"),
      HaiQuestionnaireOption("throat_swab", "Throat swab"),
      HaiQuestionnaireOption("csf", "CSF"),
      HaiQuestionnaireOption("eye_swab", "Eye swab"),
      HaiQuestionnaireOption("ear_swab", "Ear swab"),
      HaiQuestionnaireOption("catheter_tip", "Catheter tip"),
      HaiQuestionnaireOption("stool_mcs", "Stool MCS"),
      HaiQuestionnaireOption("others", "Others"),
      HaiQuestionnaireOption("aspirate", "Aspirate"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_61_Was_proper_sampl_n_technique_followed",
    label: "61. Was proper sample collection technique followed?",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${_45_Specimen_collected} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
      HaiQuestionnaireOption("not_applicable", "Not Applicable"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Microorganism",
    label: "62. Microorganism",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant:
        r"${_44_Do_the_same_patient_have_a} = 'yes' or ${_45_Specimen_collected} = 'yes'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Pathogen_Identified",
    label: "63. Pathogen Identified",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Microorganism} = 'yes'",
    options: [
      HaiQuestionnaireOption("acinetobacter_spp", "Acinetobacter Spp."),
      HaiQuestionnaireOption("aeromonas_spp", "Aeromonas Spp."),
      HaiQuestionnaireOption("achromobacter_spp", "Achromobacter Spp."),
      HaiQuestionnaireOption("agrobacterium_spp", "Agrobacterium Spp."),
      HaiQuestionnaireOption("alcaligenes_spp", "Alcaligenes Spp."),
      HaiQuestionnaireOption("bacillus_sp", "Bacillus Spp."),
      HaiQuestionnaireOption("burkholderia_cepacia", "Burkholderia cepacia"),
      HaiQuestionnaireOption("corynebacterium_spp", "Corynebacterium Spp."),
      HaiQuestionnaireOption("candida_spp", "Candida Spp."),
      HaiQuestionnaireOption("escherichia_coli", "Escherichia Coli"),
      HaiQuestionnaireOption("enterobacter_spp", "Enterobacter Spp."),
      HaiQuestionnaireOption(
        "gram_positive_bacilli__not_spe",
        "Gram-positive bacilli, not specified",
      ),
      HaiQuestionnaireOption(
        "other_gram_positive_bacilli",
        "Other gram-positive bacilli",
      ),
      HaiQuestionnaireOption("enterococcus_spp", "Enterococcus Spp."),
      HaiQuestionnaireOption(
        "gram_positive_cocci__not_speci",
        "Gram-positive cocci, not specified",
      ),
      HaiQuestionnaireOption(
        "other_gram_positive_cocci",
        "Other Gram-positive cocci",
      ),
      HaiQuestionnaireOption("citrobacter_spp", "Citrobacter Spp."),
      HaiQuestionnaireOption("haemophilus_influenza", "Haemophilus Spp."),
      HaiQuestionnaireOption("klebsiella_spp", "Klebsiella Spp."),
      HaiQuestionnaireOption("lactobacillus_spp", "Lactobacillus spp."),
      HaiQuestionnaireOption(
        "listeria_monocytogenes",
        "Listeria monocytogenes",
      ),
      HaiQuestionnaireOption("legionella_spp", "Legionella spp."),
      HaiQuestionnaireOption("morganella_spp", "Morganella spp."),
      HaiQuestionnaireOption("neisseria_meningitides", "Neisseria Spp."),
      HaiQuestionnaireOption(
        "gram_negative_cocci__not_speci",
        "Gram-negative cocci, not specified",
      ),
      HaiQuestionnaireOption(
        "other_gram_negative_cocci",
        "Other gram-negative cocci",
      ),
      HaiQuestionnaireOption("staphylococcus_spp", "Staphylococcus Spp."),
      HaiQuestionnaireOption(
        "coagulase_negative_staphylococ",
        "Coagulase-negative staphylococci, not specified",
      ),
      HaiQuestionnaireOption(
        "other_coagulase_negative_staph",
        "Other coagulase-negative staphylococci (CNS)",
      ),
      HaiQuestionnaireOption("streptococcus_spp", "Streptococcus Spp."),
      HaiQuestionnaireOption("proteus_spp", "Proteus Spp."),
      HaiQuestionnaireOption("pseudomonas_spp", "Pseudomonas Spp."),
      HaiQuestionnaireOption("providencia_spp", "Providencia spp."),
      HaiQuestionnaireOption("salmonella_spp", "Salmonella Spp."),
      HaiQuestionnaireOption("shigella_spp", "Shigella Spp."),
      HaiQuestionnaireOption("serratia_spp", "Serratia Spp."),
      HaiQuestionnaireOption("flavobacterium_spp", "Flavobacterium spp."),
      HaiQuestionnaireOption("campylobacter_spp", "Campylobacter spp."),
      HaiQuestionnaireOption(
        "enterobacterales__not_specifie",
        "Enterobacterales, not specified",
      ),
      HaiQuestionnaireOption(
        "other_enterobacterales",
        "Other enterobacterales",
      ),
      HaiQuestionnaireOption("yersinia_spp", "Yersinia spp."),
      HaiQuestionnaireOption(
        "stenotrophomonas_maltophilia",
        "Stenotrophomonas maltophilia",
      ),
      HaiQuestionnaireOption("gardnerella_spp", "Gardnerella spp."),
      HaiQuestionnaireOption("helicobacter_pylori", "Helicobacter pylori"),
      HaiQuestionnaireOption("pasteurella_spp", "Pasteurella spp."),
      HaiQuestionnaireOption(
        "clostridioides_difficile",
        "Clostridioides difficile",
      ),
      HaiQuestionnaireOption("clostridioides_other", "Clostridioides other"),
      HaiQuestionnaireOption(
        "mycobacterium__atypical",
        "Mycobacterium, atypical",
      ),
      HaiQuestionnaireOption(
        "mycobacterium_tuberculosis_com",
        "Mycobacterium tuberculosis complex",
      ),
      HaiQuestionnaireOption("chlamydia_spp", "Chlamydia spp."),
      HaiQuestionnaireOption("actinomyces_spp", "Actinomyces spp."),
      HaiQuestionnaireOption("nocardia_spp", "Nocardia spp."),
      HaiQuestionnaireOption("aspergillus_fumigatus", "Aspergillus Spp."),
      HaiQuestionnaireOption("option_54", "Burkholederia spp"),
      HaiQuestionnaireOption("sphingomonas_spp", "Sphingomonas spp"),
      HaiQuestionnaireOption("kocuria_spp", "Kocuria spp"),
      HaiQuestionnaireOption(
        "microorganism_not_identified",
        "Microorganism not identified",
      ),
      HaiQuestionnaireOption("examination_not_done", "Examination not done"),
      HaiQuestionnaireOption("sterile_examination", "Sterile examination"),
      HaiQuestionnaireOption(
        "result_not__yet__available_or_",
        "Result not (yet) available or missing",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_64_Sub_specy",
    label: "64. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'acinetobacter_spp'",
    options: [
      HaiQuestionnaireOption(
        "acinetobacter_baumannii",
        "Acinetobacter baumannii",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_baumannii_1",
        "Acinetobacter baumannii",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_calcoaceticus",
        "Acinetobacter calcoaceticus",
      ),
      HaiQuestionnaireOption("acinetobacter_lwoffii", "Acinetobacter lwoffii"),
      HaiQuestionnaireOption(
        "acinetobacter_haemolyticus",
        "Acinetobacter haemolyticus",
      ),
      HaiQuestionnaireOption("achromobacter_spp", "Achromobacter spp."),
      HaiQuestionnaireOption("acinetobacter_junii", "Acinetobacter junii"),
      HaiQuestionnaireOption(
        "acinetobacter_radioresistens",
        "Acinetobacter radioresistens",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_johnsonii",
        "Acinetobacter johnsonii",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_spp__other",
        "Acinetobacter spp., other",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_spp__not_specified",
        "Acinetobacter spp., Not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_65_Sub_specy",
    label: "65. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'candida_spp'",
    options: [
      HaiQuestionnaireOption("candida_albicans", "Candida albicans"),
      HaiQuestionnaireOption("candida_glabrata", "Candida glabrata"),
      HaiQuestionnaireOption("candida_tropicalis", "Candida tropicalis"),
      HaiQuestionnaireOption("candida_parapsilosis", "Candida parapsilosis"),
      HaiQuestionnaireOption("candida_krusei", "Candida krusei"),
      HaiQuestionnaireOption("candida_auris", "Candida auris"),
      HaiQuestionnaireOption("candida_lusitaniae", "Candida lusitaniae"),
      HaiQuestionnaireOption("candida_dubliniensis", "Candida dubliniensis"),
      HaiQuestionnaireOption("candida_rugosa", "Candida rugosa"),
      HaiQuestionnaireOption(
        "candida_guilliermondii",
        "Candida guilliermondii",
      ),
      HaiQuestionnaireOption("candida_haemulonii", "Candida haemulonii"),
      HaiQuestionnaireOption("candida_spp__other", "Candida spp., other"),
      HaiQuestionnaireOption(
        "candida_spp__not_specified",
        "Candida spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_66_Sub_specy",
    label: "66. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'enterobacter_spp'",
    options: [
      HaiQuestionnaireOption("enterobacter_cloacae", "Enterobacter cloacae"),
      HaiQuestionnaireOption(
        "enterobacter_hormaechei",
        "Enterobacter hormaechei",
      ),
      HaiQuestionnaireOption(
        "enterobacter_aerogenes",
        "Enterobacter aerogenes",
      ),
      HaiQuestionnaireOption(
        "enterobacter_agglomerans",
        "Enterobacter agglomerans",
      ),
      HaiQuestionnaireOption(
        "enterobacter_sakazakii",
        "Enterobacter sakazakii",
      ),
      HaiQuestionnaireOption(
        "enterobacter_gergoviae",
        "Enterobacter gergoviae",
      ),
      HaiQuestionnaireOption("enterobacter_ludwigii", "Enterobacter ludwigii"),
      HaiQuestionnaireOption(
        "enterobacter_spp__other",
        "Enterobacter spp., other",
      ),
      HaiQuestionnaireOption(
        "enterobacter_spp__not_specified",
        "Enterobacter spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_67_Sub_specy",
    label: "67. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'enterococcus_spp'",
    options: [
      HaiQuestionnaireOption("enterococcus_faecalis", "Enterococcus faecalis"),
      HaiQuestionnaireOption("enterococcus_faecium", "Enterococcus faecium"),
      HaiQuestionnaireOption(
        "enterococcus_spp__other",
        "Enterococcus spp., other",
      ),
      HaiQuestionnaireOption(
        "enterococcus_spp__not_specified",
        "Enterococcus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_68_Sub_specy",
    label: "68. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'citrobacter_spp'",
    options: [
      HaiQuestionnaireOption("citrobacter_freundii", "Citrobacter freundii"),
      HaiQuestionnaireOption(
        "citrobacter_koseri__e_g__diversus",
        "Citrobacter koseri (e.g. diversus)",
      ),
      HaiQuestionnaireOption(
        "citrobacter_spp__other",
        "Citrobacter spp., other",
      ),
      HaiQuestionnaireOption(
        "citrobacter_spp__not_specified",
        "Citrobacter spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_69_Sub_specy",
    label: "69. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'klebsiella_spp'",
    options: [
      HaiQuestionnaireOption("klebsiella_pneumoniae", "Klebsiella pneumoniae"),
      HaiQuestionnaireOption("klebsiella_oxytoca", "Klebsiella oxytoca"),
      HaiQuestionnaireOption("klebsiella_spp__other", "Klebsiella spp., other"),
      HaiQuestionnaireOption(
        "klebsiella_spp__not_specified",
        "Klebsiella spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_70_Sub_specy",
    label: "70. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'haemophilus_influenza'",
    options: [
      HaiQuestionnaireOption("haemophilus_influenza", "Haemophilus influenza"),
      HaiQuestionnaireOption(
        "haemophilus_parainfluenzae",
        "Haemophilus parainfluenzae",
      ),
      HaiQuestionnaireOption(
        "haemophilus_spp__other",
        "Haemophilus spp., other",
      ),
      HaiQuestionnaireOption(
        "haemophilus_spp__not_specified",
        "Haemophilus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_71_Sub_specy",
    label: "71. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'neisseria_meningitides'",
    options: [
      HaiQuestionnaireOption(
        "neisseria_meningitides",
        "Neisseria meningitides",
      ),
      HaiQuestionnaireOption("neisseria_spp__other", "Neisseria spp., other"),
      HaiQuestionnaireOption(
        "neisseria_spp__not_specified",
        "Neisseria spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_72_Sub_specy",
    label: "72. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'staphylococcus_spp'",
    options: [
      HaiQuestionnaireOption("staphylococcus_aureus", "Staphylococcus aureus"),
      HaiQuestionnaireOption(
        "staphylococcus_epidermidis",
        "Staphylococcus epidermidis",
      ),
      HaiQuestionnaireOption(
        "staphylococcus_haemolyticus",
        "Staphylococcus haemolyticus",
      ),
      HaiQuestionnaireOption(
        "staphylococcus_spp__not_specified",
        "Staphylococcus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_73_Sub_specy",
    label: "73. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'streptococcus_spp'",
    options: [
      HaiQuestionnaireOption(
        "streptococcus_pneumoniae",
        "Streptococcus pneumoniae",
      ),
      HaiQuestionnaireOption(
        "streptococcus_pyogenes__a",
        "Streptococcus pyogenes (A)",
      ),
      HaiQuestionnaireOption(
        "streptococcus_agalactiae__b",
        "Streptococcus agalactiae (B)",
      ),
      HaiQuestionnaireOption(
        "other_haemolytic_streptococci__c__g",
        "Other haemolytic streptococci (C, G)",
      ),
      HaiQuestionnaireOption(
        "streptococcus_spp__other",
        "Streptococcus spp., other",
      ),
      HaiQuestionnaireOption(
        "streptococcus_spp__not_specified",
        "Streptococcus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_74_Sub_specy",
    label: "74. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'proteus_spp'",
    options: [
      HaiQuestionnaireOption("proteus_mirabilis", "Proteus mirabilis"),
      HaiQuestionnaireOption("proteus_vulgaris", "Proteus vulgaris"),
      HaiQuestionnaireOption("proteus_spp__other", "Proteus spp., other"),
      HaiQuestionnaireOption(
        "proteus_spp__not_specified",
        "Proteus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_75_Sub_specy",
    label: "75. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'pseudomonas_spp'",
    options: [
      HaiQuestionnaireOption(
        "pseudomonas_aeruginosa",
        "Pseudomonas aeruginosa",
      ),
      HaiQuestionnaireOption(
        "pseudomonadaceae_family__other",
        "Pseudomonadaceae family, other",
      ),
      HaiQuestionnaireOption(
        "pseudomonadaceae_family__not_specified",
        "Pseudomonadaceae family, not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_76_Sub_specy",
    label: "76. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'salmonella_spp'",
    options: [
      HaiQuestionnaireOption(
        "salmonella_enteritidis",
        "Salmonella Enteritidis",
      ),
      HaiQuestionnaireOption(
        "salmonella_typhi_or_paratyphi",
        "Salmonella Typhi or Paratyphi",
      ),
      HaiQuestionnaireOption(
        "salmonella_typhimurium",
        "Salmonella Typhimurium",
      ),
      HaiQuestionnaireOption(
        "salmonella_spp__not_specified",
        "Salmonella spp., not specified",
      ),
      HaiQuestionnaireOption("salmonella_spp__other", "Salmonella spp., other"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_77_Sub_specy",
    label: "77. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'serratia_spp'",
    options: [
      HaiQuestionnaireOption("serratia_marcescens", "Serratia marcescens"),
      HaiQuestionnaireOption("serratia_liquefaciens", "Serratia liquefaciens"),
      HaiQuestionnaireOption("serratia_spp__other", "Serratia spp., other"),
      HaiQuestionnaireOption(
        "serratia_spp__not_specified",
        "Serratia spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_78_Sub_specy",
    label: "78. Sub-specy",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'aspergillus_fumigatus'",
    options: [
      HaiQuestionnaireOption("aspergillus_niger", "Aspergillus niger"),
      HaiQuestionnaireOption("aspergillus_fumigatus", "Aspergillus fumigatus"),
      HaiQuestionnaireOption(
        "aspergillus_spp__other",
        "Aspergillus spp., other",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_79_Resistant_Pattern",
    label: "79. Resistant Pattern",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant:
        r"${Pathogen_Identified} = 'acinetobacter_spp' or ${Pathogen_Identified} = 'pseudomonas_spp'",
    options: [
      HaiQuestionnaireOption("car", "CAR"),
      HaiQuestionnaireOption("mdr", "MDR"),
      HaiQuestionnaireOption("no_resistant_type", "No Resistant Type"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_80_Resistant_Pattern",
    label: "80. Resistant Pattern",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant:
        r"${Pathogen_Identified} = 'escherichia_coli' or ${Pathogen_Identified} = 'enterobacter_spp' or ${Pathogen_Identified} = 'citrobacter_spp' or ${Pathogen_Identified} = 'klebsiella_spp' or ${Pathogen_Identified} = 'morganella_spp' or ${Pathogen_Identified} = 'proteus_spp' or ${Pathogen_Identified} = 'serratia_spp'",
    options: [
      HaiQuestionnaireOption("c3g", "C3G"),
      HaiQuestionnaireOption("car", "CAR"),
      HaiQuestionnaireOption("mdr", "MDR"),
      HaiQuestionnaireOption("no_resistant_type", "No Resistant type"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_81_Resistant_Pattern",
    label: "81. Resistant Pattern",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified} = 'enterococcus_spp'",
    options: [
      HaiQuestionnaireOption("vre", "VRE"),
      HaiQuestionnaireOption("lre", "LRE"),
      HaiQuestionnaireOption("mdr", "MDR"),
      HaiQuestionnaireOption("no_resistant_type", "No Resistant type"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_82_Resistant_Pattern",
    label: "82. Resistant Pattern",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant:
        r"${Pathogen_Identified} = 'staphylococcus_spp' or ${Pathogen_Identified} = 'coagulase_negative_staphylococ' or ${Pathogen_Identified} = 'other_coagulase_negative_staph'",
    options: [
      HaiQuestionnaireOption("mrsa", "MRSA"),
      HaiQuestionnaireOption("vrsa", "VRSA"),
      HaiQuestionnaireOption("mdr", "MDR"),
      HaiQuestionnaireOption("no_resistant_type", "No Resistant type"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_83_Type_of_Sample_Collected_2",
    label: "83. Type of Sample Collected 2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant:
        r"${From_the_same_sample} = 'no' or ${_44_Do_the_same_patient_have_a} = 'yes'",
    options: [
      HaiQuestionnaireOption("wound_swab", "Wound swab"),
      HaiQuestionnaireOption("urine", "Urine"),
      HaiQuestionnaireOption("blood", "Blood"),
      HaiQuestionnaireOption("sputum", "Sputum"),
      HaiQuestionnaireOption("tracheal_aspirate", "Tracheal aspirate"),
      HaiQuestionnaireOption("tissue_mcs", "Tissue MCS"),
      HaiQuestionnaireOption("bone_mcs", "Bone MCS"),
      HaiQuestionnaireOption("throat_swab", "Throat swab"),
      HaiQuestionnaireOption("csf", "CSF"),
      HaiQuestionnaireOption("eye_swab", "Eye swab"),
      HaiQuestionnaireOption("ear_swab", "Ear swab"),
      HaiQuestionnaireOption("catheter_tip", "Catheter tip"),
      HaiQuestionnaireOption("stool_mcs", "Stool MCS"),
      HaiQuestionnaireOption("others", "Others"),
      HaiQuestionnaireOption("aspirate", "Aspirate"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Pathogen_Identified_001",
    label: "84. Pathogen Identified2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant:
        r"${From_the_same_sample} = 'no' or ${From_the_same_sample} = 'yes' or ${_44_Do_the_same_patient_have_a} = 'yes'",
    options: [
      HaiQuestionnaireOption("acinetobacter_spp", "Acinetobacter Spp."),
      HaiQuestionnaireOption("aeromonas_spp", "Aeromonas Spp."),
      HaiQuestionnaireOption("achromobacter_spp", "Achromobacter Spp."),
      HaiQuestionnaireOption("agrobacterium_spp", "Agrobacterium Spp."),
      HaiQuestionnaireOption("alcaligenes_spp", "Alcaligenes Spp."),
      HaiQuestionnaireOption("bacillus_sp", "Bacillus Spp."),
      HaiQuestionnaireOption("burkholderia_cepacia", "Burkholderia cepacia"),
      HaiQuestionnaireOption("corynebacterium_spp", "Corynebacterium Spp."),
      HaiQuestionnaireOption("candida_spp", "Candida Spp."),
      HaiQuestionnaireOption("escherichia_coli", "Escherichia Coli"),
      HaiQuestionnaireOption("enterobacter_spp", "Enterobacter Spp."),
      HaiQuestionnaireOption(
        "gram_positive_bacilli__not_spe",
        "Gram-positive bacilli, not specified",
      ),
      HaiQuestionnaireOption(
        "other_gram_positive_bacilli",
        "Other gram-positive bacilli",
      ),
      HaiQuestionnaireOption("enterococcus_spp", "Enterococcus Spp."),
      HaiQuestionnaireOption(
        "gram_positive_cocci__not_speci",
        "Gram-positive cocci, not specified",
      ),
      HaiQuestionnaireOption(
        "other_gram_positive_cocci",
        "Other Gram-positive cocci",
      ),
      HaiQuestionnaireOption("citrobacter_spp", "Citrobacter Spp."),
      HaiQuestionnaireOption("haemophilus_influenza", "Haemophilus Spp."),
      HaiQuestionnaireOption("klebsiella_spp", "Klebsiella Spp."),
      HaiQuestionnaireOption("lactobacillus_spp", "Lactobacillus spp."),
      HaiQuestionnaireOption(
        "listeria_monocytogenes",
        "Listeria monocytogenes",
      ),
      HaiQuestionnaireOption("legionella_spp", "Legionella spp."),
      HaiQuestionnaireOption("morganella_spp", "Morganella spp."),
      HaiQuestionnaireOption("neisseria_meningitides", "Neisseria Spp."),
      HaiQuestionnaireOption(
        "gram_negative_cocci__not_speci",
        "Gram-negative cocci, not specified",
      ),
      HaiQuestionnaireOption(
        "other_gram_negative_cocci",
        "Other gram-negative cocci",
      ),
      HaiQuestionnaireOption("staphylococcus_spp", "Staphylococcus Spp."),
      HaiQuestionnaireOption(
        "coagulase_negative_staphylococ",
        "Coagulase-negative staphylococci, not specified",
      ),
      HaiQuestionnaireOption(
        "other_coagulase_negative_staph",
        "Other coagulase-negative staphylococci (CNS)",
      ),
      HaiQuestionnaireOption("streptococcus_spp", "Streptococcus Spp."),
      HaiQuestionnaireOption("proteus_spp", "Proteus Spp."),
      HaiQuestionnaireOption("pseudomonas_spp", "Pseudomonas Spp."),
      HaiQuestionnaireOption("providencia_spp", "Providencia spp."),
      HaiQuestionnaireOption("salmonella_spp", "Salmonella Spp."),
      HaiQuestionnaireOption("shigella_spp", "Shigella Spp."),
      HaiQuestionnaireOption("serratia_spp", "Serratia Spp."),
      HaiQuestionnaireOption("flavobacterium_spp", "Flavobacterium spp."),
      HaiQuestionnaireOption("campylobacter_spp", "Campylobacter spp."),
      HaiQuestionnaireOption(
        "enterobacterales__not_specifie",
        "Enterobacterales, not specified",
      ),
      HaiQuestionnaireOption(
        "other_enterobacterales",
        "Other enterobacterales",
      ),
      HaiQuestionnaireOption("yersinia_spp", "Yersinia spp."),
      HaiQuestionnaireOption(
        "stenotrophomonas_maltophilia",
        "Stenotrophomonas maltophilia",
      ),
      HaiQuestionnaireOption("gardnerella_spp", "Gardnerella spp."),
      HaiQuestionnaireOption("helicobacter_pylori", "Helicobacter pylori"),
      HaiQuestionnaireOption("pasteurella_spp", "Pasteurella spp."),
      HaiQuestionnaireOption(
        "clostridioides_difficile",
        "Clostridioides difficile",
      ),
      HaiQuestionnaireOption("clostridioides_other", "Clostridioides other"),
      HaiQuestionnaireOption(
        "mycobacterium__atypical",
        "Mycobacterium, atypical",
      ),
      HaiQuestionnaireOption(
        "mycobacterium_tuberculosis_com",
        "Mycobacterium tuberculosis complex",
      ),
      HaiQuestionnaireOption("chlamydia_spp", "Chlamydia spp."),
      HaiQuestionnaireOption("actinomyces_spp", "Actinomyces spp."),
      HaiQuestionnaireOption("nocardia_spp", "Nocardia spp."),
      HaiQuestionnaireOption("aspergillus_fumigatus", "Aspergillus Spp."),
      HaiQuestionnaireOption("option_54", "Burkholederia spp"),
      HaiQuestionnaireOption("sphingomonas_spp", "Sphingomonas spp"),
      HaiQuestionnaireOption("kocuria_spp", "Kocuria spp"),
      HaiQuestionnaireOption(
        "microorganism_not_identified",
        "Microorganism not identified",
      ),
      HaiQuestionnaireOption("examination_not_done", "Examination not done"),
      HaiQuestionnaireOption("sterile_examination", "Sterile examination"),
      HaiQuestionnaireOption(
        "result_not__yet__available_or_",
        "Result not (yet) available or missing",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_85_Sub_specy2",
    label: "85. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'acinetobacter_spp'",
    options: [
      HaiQuestionnaireOption(
        "acinetobacter_baumannii",
        "Acinetobacter baumannii",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_baumannii_1",
        "Acinetobacter baumannii",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_calcoaceticus",
        "Acinetobacter calcoaceticus",
      ),
      HaiQuestionnaireOption("acinetobacter_lwoffii", "Acinetobacter lwoffii"),
      HaiQuestionnaireOption(
        "acinetobacter_haemolyticus",
        "Acinetobacter haemolyticus",
      ),
      HaiQuestionnaireOption("achromobacter_spp", "Achromobacter spp."),
      HaiQuestionnaireOption("acinetobacter_junii", "Acinetobacter junii"),
      HaiQuestionnaireOption(
        "acinetobacter_radioresistens",
        "Acinetobacter radioresistens",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_johnsonii",
        "Acinetobacter johnsonii",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_spp__other",
        "Acinetobacter spp., other",
      ),
      HaiQuestionnaireOption(
        "acinetobacter_spp__not_specified",
        "Acinetobacter spp., Not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_86_Sub_specy2",
    label: "86. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'candida_spp'",
    options: [
      HaiQuestionnaireOption("candida_albicans", "Candida albicans"),
      HaiQuestionnaireOption("candida_glabrata", "Candida glabrata"),
      HaiQuestionnaireOption("candida_tropicalis", "Candida tropicalis"),
      HaiQuestionnaireOption("candida_parapsilosis", "Candida parapsilosis"),
      HaiQuestionnaireOption("candida_krusei", "Candida krusei"),
      HaiQuestionnaireOption("candida_auris", "Candida auris"),
      HaiQuestionnaireOption("candida_lusitaniae", "Candida lusitaniae"),
      HaiQuestionnaireOption("candida_dubliniensis", "Candida dubliniensis"),
      HaiQuestionnaireOption("candida_rugosa", "Candida rugosa"),
      HaiQuestionnaireOption(
        "candida_guilliermondii",
        "Candida guilliermondii",
      ),
      HaiQuestionnaireOption("candida_haemulonii", "Candida haemulonii"),
      HaiQuestionnaireOption("candida_spp__other", "Candida spp., other"),
      HaiQuestionnaireOption(
        "candida_spp__not_specified",
        "Candida spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_87_Sub_specy2",
    label: "87. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'enterobacter_spp'",
    options: [
      HaiQuestionnaireOption("enterobacter_cloacae", "Enterobacter cloacae"),
      HaiQuestionnaireOption(
        "enterobacter_hormaechei",
        "Enterobacter hormaechei",
      ),
      HaiQuestionnaireOption(
        "enterobacter_aerogenes",
        "Enterobacter aerogenes",
      ),
      HaiQuestionnaireOption(
        "enterobacter_agglomerans",
        "Enterobacter agglomerans",
      ),
      HaiQuestionnaireOption(
        "enterobacter_sakazakii",
        "Enterobacter sakazakii",
      ),
      HaiQuestionnaireOption(
        "enterobacter_gergoviae",
        "Enterobacter gergoviae",
      ),
      HaiQuestionnaireOption("enterobacter_ludwigii", "Enterobacter ludwigii"),
      HaiQuestionnaireOption(
        "enterobacter_spp__other",
        "Enterobacter spp., other",
      ),
      HaiQuestionnaireOption(
        "enterobacter_spp__not_specified",
        "Enterobacter spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_88_Sub_specy2",
    label: "88. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'enterococcus_spp'",
    options: [
      HaiQuestionnaireOption("enterococcus_faecalis", "Enterococcus faecalis"),
      HaiQuestionnaireOption("enterococcus_faecium", "Enterococcus faecium"),
      HaiQuestionnaireOption(
        "enterococcus_spp__other",
        "Enterococcus spp., other",
      ),
      HaiQuestionnaireOption(
        "enterococcus_spp__not_specified",
        "Enterococcus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_89_Sub_specy2",
    label: "89. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'citrobacter_spp'",
    options: [
      HaiQuestionnaireOption("citrobacter_freundii", "Citrobacter freundii"),
      HaiQuestionnaireOption(
        "citrobacter_koseri__e_g__diversus",
        "Citrobacter koseri (e.g. diversus)",
      ),
      HaiQuestionnaireOption(
        "citrobacter_spp__other",
        "Citrobacter spp., other",
      ),
      HaiQuestionnaireOption(
        "citrobacter_spp__not_specified",
        "Citrobacter spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_90_Sub_specy2",
    label: "90. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'haemophilus_influenza'",
    options: [
      HaiQuestionnaireOption("haemophilus_influenza", "Haemophilus influenza"),
      HaiQuestionnaireOption(
        "haemophilus_parainfluenzae",
        "Haemophilus parainfluenzae",
      ),
      HaiQuestionnaireOption(
        "haemophilus_spp__other",
        "Haemophilus spp., other",
      ),
      HaiQuestionnaireOption(
        "haemophilus_spp__not_specified",
        "Haemophilus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_91_Sub_specy2",
    label: "91. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'haemophilus_influenza'",
    options: [
      HaiQuestionnaireOption("haemophilus_influenza", "Haemophilus influenza"),
      HaiQuestionnaireOption(
        "haemophilus_parainfluenzae",
        "Haemophilus parainfluenzae",
      ),
      HaiQuestionnaireOption(
        "haemophilus_spp__other",
        "Haemophilus spp., other",
      ),
      HaiQuestionnaireOption(
        "haemophilus_spp__not_specified",
        "Haemophilus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_92_Sub_specy2",
    label: "92. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'neisseria_meningitides'",
    options: [
      HaiQuestionnaireOption(
        "neisseria_meningitides",
        "Neisseria meningitides",
      ),
      HaiQuestionnaireOption("neisseria_spp__other", "Neisseria spp., other"),
      HaiQuestionnaireOption(
        "neisseria_spp__not_specified",
        "Neisseria spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_93_Sub_specy2",
    label: "93. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'staphylococcus_spp'",
    options: [
      HaiQuestionnaireOption("staphylococcus_aureus", "Staphylococcus aureus"),
      HaiQuestionnaireOption(
        "staphylococcus_epidermidis",
        "Staphylococcus epidermidis",
      ),
      HaiQuestionnaireOption(
        "staphylococcus_haemolyticus",
        "Staphylococcus haemolyticus",
      ),
      HaiQuestionnaireOption(
        "staphylococcus_spp__not_specified",
        "Staphylococcus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_94_Sub_specy2",
    label: "94. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'streptococcus_spp'",
    options: [
      HaiQuestionnaireOption(
        "streptococcus_pneumoniae",
        "Streptococcus pneumoniae",
      ),
      HaiQuestionnaireOption(
        "streptococcus_pyogenes__a",
        "Streptococcus pyogenes (A)",
      ),
      HaiQuestionnaireOption(
        "streptococcus_agalactiae__b",
        "Streptococcus agalactiae (B)",
      ),
      HaiQuestionnaireOption(
        "other_haemolytic_streptococci__c__g",
        "Other haemolytic streptococci (C, G)",
      ),
      HaiQuestionnaireOption(
        "streptococcus_spp__other",
        "Streptococcus spp., other",
      ),
      HaiQuestionnaireOption(
        "streptococcus_spp__not_specified",
        "Streptococcus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_95_Sub_specy2",
    label: "95. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'proteus_spp'",
    options: [
      HaiQuestionnaireOption("proteus_mirabilis", "Proteus mirabilis"),
      HaiQuestionnaireOption("proteus_vulgaris", "Proteus vulgaris"),
      HaiQuestionnaireOption("proteus_spp__other", "Proteus spp., other"),
      HaiQuestionnaireOption(
        "proteus_spp__not_specified",
        "Proteus spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_96_Sub_specy2",
    label: "96. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'pseudomonas_spp'",
    options: [
      HaiQuestionnaireOption(
        "pseudomonas_aeruginosa",
        "Pseudomonas aeruginosa",
      ),
      HaiQuestionnaireOption(
        "pseudomonadaceae_family__other",
        "Pseudomonadaceae family, other",
      ),
      HaiQuestionnaireOption(
        "pseudomonadaceae_family__not_specified",
        "Pseudomonadaceae family, not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_97_Sub_specy2",
    label: "97. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'salmonella_spp'",
    options: [
      HaiQuestionnaireOption(
        "salmonella_enteritidis",
        "Salmonella Enteritidis",
      ),
      HaiQuestionnaireOption(
        "salmonella_typhi_or_paratyphi",
        "Salmonella Typhi or Paratyphi",
      ),
      HaiQuestionnaireOption(
        "salmonella_typhimurium",
        "Salmonella Typhimurium",
      ),
      HaiQuestionnaireOption(
        "salmonella_spp__not_specified",
        "Salmonella spp., not specified",
      ),
      HaiQuestionnaireOption("salmonella_spp__other", "Salmonella spp., other"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_98_Sub_specy2",
    label: "98. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'serratia_spp'",
    options: [
      HaiQuestionnaireOption("serratia_marcescens", "Serratia marcescens"),
      HaiQuestionnaireOption("serratia_liquefaciens", "Serratia liquefaciens"),
      HaiQuestionnaireOption("serratia_spp__other", "Serratia spp., other"),
      HaiQuestionnaireOption(
        "serratia_spp__not_specified",
        "Serratia spp., not specified",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_99_Sub_specy2",
    label: "99. Sub-specy2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'aspergillus_fumigatus'",
    options: [
      HaiQuestionnaireOption("aspergillus_niger", "Aspergillus niger"),
      HaiQuestionnaireOption("aspergillus_fumigatus", "Aspergillus fumigatus"),
      HaiQuestionnaireOption(
        "aspergillus_spp__other",
        "Aspergillus spp., other",
      ),
    ],
  ),
  HaiQuestionnaireField(
    name: "_100_Resistant_Pattern2",
    label: "100. Resistant Pattern2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant:
        r"${Pathogen_Identified_001} = 'acinetobacter_spp' or ${Pathogen_Identified_001} = 'pseudomonas_spp'",
    options: [
      HaiQuestionnaireOption("car", "CAR"),
      HaiQuestionnaireOption("mdr", "MDR"),
      HaiQuestionnaireOption("no_resistant_type", "No Resistant Type"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_101_Resistant_Pattern2",
    label: "101. Resistant Pattern2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant:
        r"${Pathogen_Identified_001} = 'escherichia_coli' or ${Pathogen_Identified_001} = 'enterobacter_spp' or ${Pathogen_Identified_001} = 'citrobacter_spp' or ${Pathogen_Identified_001} = 'klebsiella_spp' or ${Pathogen_Identified_001} = 'morganella_spp' or ${Pathogen_Identified_001} = 'proteus_spp' or ${Pathogen_Identified_001} = 'serratia_spp'",
    options: [
      HaiQuestionnaireOption("c3g", "C3G"),
      HaiQuestionnaireOption("car", "CAR"),
      HaiQuestionnaireOption("mdr", "MDR"),
      HaiQuestionnaireOption("no_resistant_type", "No Resistant type"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_102_Resistant_Pattern2",
    label: "102. Resistant Pattern2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant: r"${Pathogen_Identified_001} = 'enterococcus_spp'",
    options: [
      HaiQuestionnaireOption("vre", "VRE"),
      HaiQuestionnaireOption("lre", "LRE"),
      HaiQuestionnaireOption("mdr", "MDR"),
      HaiQuestionnaireOption("no_resistant_type", "No Resistant type"),
    ],
  ),
  HaiQuestionnaireField(
    name: "_103_Resistant_Pattern2",
    label: "103. Resistant Pattern2",
    section: "Patient Microorganism",
    type: "select",
    required: true,
    relevant:
        r"${Pathogen_Identified_001} = 'staphylococcus_spp' or ${Pathogen_Identified_001} = 'coagulase_negative_staphylococ' or ${Pathogen_Identified_001} = 'other_coagulase_negative_staph'",
    options: [
      HaiQuestionnaireOption("mrsa", "MRSA"),
      HaiQuestionnaireOption("vrsa", "VRSA"),
      HaiQuestionnaireOption("mdr", "MDR"),
      HaiQuestionnaireOption("no_resistant_type", "No Resistant type"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Clinical_Outcome",
    label: "Clinical Outcome",
    section: "Patient Microorganism",
    type: "select",
    options: [
      HaiQuestionnaireOption("recovered", "Recovered"),
      HaiQuestionnaireOption("improved", "Improved"),
      HaiQuestionnaireOption("not_improved", "Not improved"),
      HaiQuestionnaireOption("deteriorated", "Deteriorated"),
      HaiQuestionnaireOption("ongoing_treatment", "Ongoing treatment"),
      HaiQuestionnaireOption("died", "Died"),
      HaiQuestionnaireOption("discharged", "Discharged"),
      HaiQuestionnaireOption("transferred", "Transferred"),
      HaiQuestionnaireOption("referred", "Referred"),
      HaiQuestionnaireOption(
        "left_against_medical_advice",
        "Left against medical advice",
      ),
      HaiQuestionnaireOption("absconded", "Absconded"),
      HaiQuestionnaireOption("still_admitted", "Still admitted"),
      HaiQuestionnaireOption("unknown", "Unknown"),
      HaiQuestionnaireOption("other", "Other"),
    ],
  ),
  HaiQuestionnaireField(
    name: "Other_Clinical_Outcome",
    label: "Specify other clinical outcome",
    section: "Patient Microorganism",
    type: "text",
    required: true,
    relevant: r"${Clinical_Outcome} = 'other'",
  ),
  HaiQuestionnaireField(
    name: "Outcome_Date",
    label: "Outcome Date",
    section: "Patient Microorganism",
    type: "date",
  ),
  HaiQuestionnaireField(
    name: "HAI_Contributed_To_Death",
    label: "Did the HAI contribute to the patient's death?",
    section: "Patient Microorganism",
    type: "select",
    relevant: r"${Clinical_Outcome} = 'died'",
    options: [
      HaiQuestionnaireOption("yes", "Yes"),
      HaiQuestionnaireOption("no", "No"),
      HaiQuestionnaireOption("unknown", "Unknown"),
    ],
  ),
  HaiQuestionnaireField(
    name: "HAI_Relationship_To_Death",
    label: "Relationship of HAI to death",
    section: "Patient Microorganism",
    type: "select",
    relevant: r"${Clinical_Outcome} = 'died'",
    options: [
      HaiQuestionnaireOption(
        "directly_caused_death",
        "HAI directly caused death",
      ),
      HaiQuestionnaireOption(
        "contributed_to_death",
        "HAI contributed to death",
      ),
      HaiQuestionnaireOption("unrelated_to_hai", "Death was unrelated to HAI"),
      HaiQuestionnaireOption("unable_to_determine", "Unable to determine"),
    ],
  ),
];

const targetedHaiRelevantSections = <String>{
  "Patient Biodata",
  "Antimicrobial data",
  "Patient Risk Factors",
  "Patient HAIs",
  "Patient Microorganism",
};
