class WaterQualityField {
  final String name;
  final String label;
  final String section;
  final String type;
  final bool required;
  final List<String> options;
  final String? hint;
  final String? visibleWhenField;
  final List<String> visibleWhenValues;
  final List<Map<String, String>> visibleWhenRules;

  const WaterQualityField({
    required this.name,
    required this.label,
    required this.section,
    this.type = 'text',
    this.required = false,
    this.options = const [],
    this.hint,
    this.visibleWhenField,
    this.visibleWhenValues = const [],
    this.visibleWhenRules = const [],
  });
}

const waterQualityFields = <WaterQualityField>[
  WaterQualityField(
    name: 'Sample_ID',
    label: 'Sample ID',
    section: 'Sample Information',
    required: true,
    hint: 'e.g. FTHG-WATER-2026-001',
  ),
  WaterQualityField(
    name: 'Sampling_Point',
    label: 'Sampling Point',
    section: 'Sample Information',
    required: true,
    hint: 'e.g. Labour ward handwashing tap',
  ),
  WaterQualityField(
    name: 'Water_Source',
    label: 'Water Source',
    section: 'Sample Information',
    type: 'select',
    required: true,
    options: [
      'Borehole',
      'Municipal',
      'Well',
      'Storage tank',
      'RO/Filtered',
      'Other',
    ],
  ),
  WaterQualityField(
    name: 'Sample_Type',
    label: 'Sample Type',
    section: 'Sample Information',
    type: 'select',
    required: true,
    options: ['Routine', 'Follow-up', 'Outbreak', 'Complaint'],
  ),
  WaterQualityField(
    name: 'Lab_Number',
    label: 'Laboratory Number',
    section: 'Sample Information',
  ),
  WaterQualityField(
    name: 'Water_Clear',
    label: 'Is the water clear?',
    section: 'Physical and IPC Assessment',
    type: 'select',
    required: true,
    options: ['Yes', 'No', 'Not Applicable'],
  ),
  WaterQualityField(
    name: 'No_Unusual_Colour',
    label: 'Is the water free from unusual colour?',
    section: 'Physical and IPC Assessment',
    type: 'select',
    required: true,
    options: ['Yes', 'No', 'Not Applicable'],
  ),
  WaterQualityField(
    name: 'No_Offensive_Odour',
    label: 'Is the water free from offensive odour?',
    section: 'Physical and IPC Assessment',
    type: 'select',
    required: true,
    options: ['Yes', 'No', 'Not Applicable'],
  ),
  WaterQualityField(
    name: 'Storage_Tank_Covered',
    label: 'Is the storage tank covered?',
    section: 'Physical and IPC Assessment',
    type: 'select',
    required: true,
    options: ['Yes', 'No', 'Not Applicable'],
  ),
  WaterQualityField(
    name: 'Tap_Clean',
    label: 'Is the tap clean?',
    section: 'Physical and IPC Assessment',
    type: 'select',
    required: true,
    options: ['Yes', 'No', 'Not Applicable'],
  ),
  WaterQualityField(
    name: 'No_Leakage',
    label: 'Is the sampling point free from leakage?',
    section: 'Physical and IPC Assessment',
    type: 'select',
    required: true,
    options: ['Yes', 'No', 'Not Applicable'],
  ),
  WaterQualityField(
    name: 'Chlorine_Available',
    label: 'Is chlorine available where required?',
    section: 'Physical and IPC Assessment',
    type: 'select',
    required: true,
    options: ['Yes', 'No', 'Not Applicable'],
  ),
  WaterQualityField(
    name: 'Colour_Result',
    label: 'Colour Result',
    section: 'Physical and Chemical Results',
    hint: 'e.g. Clear',
  ),
  WaterQualityField(
    name: 'Turbidity_Result',
    label: 'Turbidity Result',
    section: 'Physical and Chemical Results',
    hint: 'e.g. Not turbid',
  ),
  WaterQualityField(
    name: 'pH',
    label: 'pH',
    section: 'Physical and Chemical Results',
    type: 'decimal',
  ),
  WaterQualityField(
    name: 'Temperature_C',
    label: 'Temperature (°C)',
    section: 'Physical and Chemical Results',
    type: 'decimal',
  ),
  WaterQualityField(
    name: 'Residual_Chlorine_mg_L',
    label: 'Residual Chlorine (mg/L)',
    section: 'Physical and Chemical Results',
    type: 'decimal',
  ),
  WaterQualityField(
    name: 'Total_Coliform',
    label: 'Total Coliform',
    section: 'Microbiology Results',
    hint: 'Enter count or Absent',
  ),
  WaterQualityField(
    name: 'E_coli',
    label: 'E. coli',
    section: 'Microbiology Results',
    type: 'select',
    required: true,
    options: ['Absent', 'Present', 'Not done'],
  ),
  WaterQualityField(
    name: 'HPC_CFU_mL',
    label: 'Heterotrophic Plate Count (CFU/mL)',
    section: 'Microbiology Results',
    type: 'integer',
  ),
  WaterQualityField(
    name: 'Culture_Done',
    label: 'Was culture performed?',
    section: 'Culture Results',
    type: 'select',
    required: true,
    options: ['Yes', 'No'],
  ),
  WaterQualityField(
    name: 'Growth_Result',
    label: 'Growth Result',
    section: 'Culture Results',
    type: 'select',
    required: true,
    options: ['No growth', 'Growth', 'Mixed growth', 'Contaminated sample'],
    visibleWhenField: 'Culture_Done',
    visibleWhenValues: ['Yes'],
  ),
  WaterQualityField(
    name: 'Organism_1',
    label: 'Organism 1',
    section: 'Culture Results',
    type: 'select',
    required: true,
    options: [
      'Escherichia coli',
      'Klebsiella pneumoniae',
      'Pseudomonas aeruginosa',
      'Acinetobacter baumannii',
      'Enterobacter cloacae',
      'Staphylococcus aureus',
      'Enterococcus spp.',
      'Candida spp.',
      'No growth',
    ],
    visibleWhenField: 'Growth_Result',
    visibleWhenValues: ['Growth', 'Mixed growth'],
  ),
  WaterQualityField(
    name: 'CFU_1',
    label: 'Organism 1 CFU',
    section: 'Culture Results',
    type: 'integer',
    visibleWhenField: 'Growth_Result',
    visibleWhenValues: ['Growth', 'Mixed growth'],
  ),
  WaterQualityField(
    name: 'Significance_1',
    label: 'Organism 1 Significance',
    section: 'Culture Results',
    type: 'select',
    required: true,
    options: [
      'Significant',
      'Likely contaminant',
      'Environmental organism',
      'Pending review',
    ],
    visibleWhenField: 'Growth_Result',
    visibleWhenValues: ['Growth', 'Mixed growth'],
  ),
  WaterQualityField(
    name: 'AST_1',
    label: 'Organism 1 AST',
    section: 'Culture Results',
    hint: 'e.g. CTX:S; CAZ:S; CIP:S; GEN:R; MEM:S',
    visibleWhenField: 'Growth_Result',
    visibleWhenValues: ['Growth', 'Mixed growth'],
  ),
  WaterQualityField(
    name: 'Organism_2',
    label: 'Organism 2 (optional)',
    section: 'Culture Results',
    type: 'select',
    options: [
      'Escherichia coli',
      'Klebsiella pneumoniae',
      'Pseudomonas aeruginosa',
      'Acinetobacter baumannii',
      'Enterobacter cloacae',
      'Staphylococcus aureus',
      'Enterococcus spp.',
      'Candida spp.',
      'No growth',
    ],
    visibleWhenField: 'Growth_Result',
    visibleWhenValues: ['Growth', 'Mixed growth'],
  ),
  WaterQualityField(
    name: 'CFU_2',
    label: 'Organism 2 CFU',
    section: 'Culture Results',
    type: 'integer',
    visibleWhenField: 'Organism_2',
    visibleWhenValues: [
      'Escherichia coli',
      'Klebsiella pneumoniae',
      'Pseudomonas aeruginosa',
      'Acinetobacter baumannii',
      'Enterobacter cloacae',
      'Staphylococcus aureus',
      'Enterococcus spp.',
      'Candida spp.',
    ],
  ),
  WaterQualityField(
    name: 'Significance_2',
    label: 'Organism 2 Significance',
    section: 'Culture Results',
    type: 'select',
    options: [
      'Significant',
      'Likely contaminant',
      'Environmental organism',
      'Pending review',
    ],
    visibleWhenField: 'Organism_2',
    visibleWhenValues: [
      'Escherichia coli',
      'Klebsiella pneumoniae',
      'Pseudomonas aeruginosa',
      'Acinetobacter baumannii',
      'Enterobacter cloacae',
      'Staphylococcus aureus',
      'Enterococcus spp.',
      'Candida spp.',
    ],
  ),
  WaterQualityField(
    name: 'AST_2',
    label: 'Organism 2 AST',
    section: 'Culture Results',
    hint: 'e.g. AMX:R; CRO:R; CIP:R; GEN:S',
    visibleWhenField: 'Organism_2',
    visibleWhenValues: [
      'Escherichia coli',
      'Klebsiella pneumoniae',
      'Pseudomonas aeruginosa',
      'Acinetobacter baumannii',
      'Enterobacter cloacae',
      'Staphylococcus aureus',
      'Enterococcus spp.',
      'Candida spp.',
    ],
  ),
  WaterQualityField(
    name: 'Organism_3',
    label: 'Organism 3 (optional)',
    section: 'Culture Results',
    type: 'select',
    options: [
      'Escherichia coli',
      'Klebsiella pneumoniae',
      'Pseudomonas aeruginosa',
      'Acinetobacter baumannii',
      'Enterobacter cloacae',
      'Staphylococcus aureus',
      'Enterococcus spp.',
      'Candida spp.',
      'No growth',
    ],
    visibleWhenField: 'Growth_Result',
    visibleWhenValues: ['Growth', 'Mixed growth'],
  ),
  WaterQualityField(
    name: 'CFU_3',
    label: 'Organism 3 CFU',
    section: 'Culture Results',
    type: 'integer',
    visibleWhenField: 'Organism_3',
    visibleWhenValues: [
      'Escherichia coli',
      'Klebsiella pneumoniae',
      'Pseudomonas aeruginosa',
      'Acinetobacter baumannii',
      'Enterobacter cloacae',
      'Staphylococcus aureus',
      'Enterococcus spp.',
      'Candida spp.',
    ],
  ),
  WaterQualityField(
    name: 'Significance_3',
    label: 'Organism 3 Significance',
    section: 'Culture Results',
    type: 'select',
    options: [
      'Significant',
      'Likely contaminant',
      'Environmental organism',
      'Pending review',
    ],
    visibleWhenField: 'Organism_3',
    visibleWhenValues: [
      'Escherichia coli',
      'Klebsiella pneumoniae',
      'Pseudomonas aeruginosa',
      'Acinetobacter baumannii',
      'Enterobacter cloacae',
      'Staphylococcus aureus',
      'Enterococcus spp.',
      'Candida spp.',
    ],
  ),
  WaterQualityField(
    name: 'AST_3',
    label: 'Organism 3 AST',
    section: 'Culture Results',
    visibleWhenField: 'Organism_3',
    visibleWhenValues: [
      'Escherichia coli',
      'Klebsiella pneumoniae',
      'Pseudomonas aeruginosa',
      'Acinetobacter baumannii',
      'Enterobacter cloacae',
      'Staphylococcus aureus',
      'Enterococcus spp.',
      'Candida spp.',
    ],
  ),
  WaterQualityField(
    name: 'Immediate_Action_Required',
    label: 'Is immediate action required?',
    section: 'Assessment and Corrective Action',
    type: 'select',
    required: true,
    options: ['Yes', 'No'],
  ),
  WaterQualityField(
    name: 'Corrective_Action',
    label: 'Corrective Action',
    section: 'Assessment and Corrective Action',
    required: true,
    visibleWhenField: 'Immediate_Action_Required',
    visibleWhenValues: ['Yes'],
  ),
  WaterQualityField(
    name: 'Department_Informed',
    label: 'Was the department informed?',
    section: 'Assessment and Corrective Action',
    type: 'select',
    required: true,
    options: ['Yes', 'No'],
  ),
  WaterQualityField(
    name: 'Follow_Up_Required',
    label: 'Is follow-up required?',
    section: 'Assessment and Corrective Action',
    type: 'select',
    required: true,
    options: ['Yes', 'No'],
  ),
  WaterQualityField(
    name: 'Remarks',
    label: 'Remarks',
    section: 'Assessment and Corrective Action',
    type: 'multiline',
  ),
];
